export type ShotClip = {
  id: string;
  event_id?: string;
  eventId?: string;
  player_name?: string;
  playerName?: string;
  video_url?: string;
  videoUrl?: string;
  thumbnail_url?: string;
  thumbnailUrl?: string;
  thumbUrl?: string | null;
  created_at?: string;
  createdAt?: string;
  ai_title?: string | null;
  ai_summary?: string | null;
  ai_tts_url?: string | null;
  aiTitle?: string | null;
  aiSummary?: string | null;
  aiTtsUrl?: string | null;
  sg_delta?: number | null;
  sgDelta?: number | null;
  anchors?: number[] | null;
  score?: number | null;
  tournamentSafe?: boolean;
  coachMode?: boolean;
  hidden?: boolean;
  visibility?: 'private' | 'event' | 'friends' | 'public';
};
