openapi: 3.0.0
info:
  title: Sample API
  version: '1.0'
paths:
  /analyze:
    post:
      summary: Analyze sample
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
