name: android-ci
on:
  pull_request:
    paths:
      - "android/**"
      - "shared/arhud/**"
      - ".github/workflows/android-ci.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept licenses
        run: yes | sdkmanager --licenses
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          cat android/local.properties
      - name: Build app & wear
        run: ./gradlew -p android :app:assembleDebug :wear:assembleDebug -S --warning-mode all
      - name: Unit tests (JVM)
        run: ./gradlew -p android :app:testDebugUnitTest :wear:testDebugUnitTest -S --warning-mode all
      - name: Lint
        run: ./gradlew -p android lint -S --warning-mode all
      - name: Upload reports (no binaries)
        uses: actions/upload-artifact@v4
        with:
          name: android-reports
          path: |
            **/build/reports/**/*
            !**/*.apk
            !**/*.aab
