name: android-ci

on:
  pull_request:
    paths:
      - 'android/**'
      - '.github/workflows/android-ci.yml'
      - 'docs/RUNBOOK_mobile.md'
  push:
    branches: [main]
    paths:
      - 'android/**'
      - '.github/workflows/android-ci.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          components: |-
            platform-tools
            platforms;android-34
            build-tools;34.0.0
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Assemble debug APK
        run: ./gradlew assembleDebug -x lint
      - name: Lint and test
        run: ./gradlew lint test
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: warn
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: android-reports
          path: |
            android/app/build/reports/**
          if-no-files-found: warn
