name: android-ci

on:
  pull_request:
    paths:
      - "android/**"
      - "shared/arhud/**"
      - ".github/workflows/android-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept licenses
        run: yes | sdkmanager --licenses
      - name: Create local.properties
        working-directory: android
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          cat local.properties
      - name: Build with Gradle (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: "8.7"
          arguments: |
            build -x lint --stacktrace
      - name: Unit tests
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: "8.7"
          arguments: |
            test --stacktrace
      - name: Lint
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: "8.7"
          arguments: |
            lint --stacktrace
      - name: Upload reports (text/HTML only)
        uses: actions/upload-artifact@v4
        with:
          name: android-reports
          path: |
            **/build/reports/**/*
            !**/*.apk
            !**/*.aab
          if-no-files-found: ignore
