name: android-ci
on:
  pull_request:
    paths:
      - "android/**"
      - "shared/arhud/**"
      - ".github/workflows/android-ci.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept licenses
        run: yes | sdkmanager --licenses
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Assemble Debug (no lint)
        working-directory: android
        run: ./gradlew assembleDebug -x lint
      - name: Lint & unit tests
        working-directory: android
        run: ./gradlew lint test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            android/app/build/outputs/**/*.apk
            android/**/reports/**
