name: Auto Merge Green PRs

on:
  # Manual + timed kicks only
  workflow_dispatch:
  schedule:
    - cron: "*/30 7-19 * * 1-5"
  # Run after CI completes on main (prevents self-trigger and noisy PR runs)
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-merge
  cancel-in-progress: false

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Only act when CI on main succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-action@v2

      - name: Find mergeable PRs (CLEAN)
        id: find
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          prs="$(gh pr list --state open \
                 --json number,isDraft,mergeStateStatus \
                 --jq '.[] | select(.isDraft==false) | select(.mergeStateStatus==\"CLEAN\") | .number' \
                 || true)"
          echo "prs=${prs}" >> "$GITHUB_OUTPUT"
          echo "count=$(wc -w <<<"$prs" | tr -d ' ')" >> "$GITHUB_OUTPUT"
          echo "Found: $prs"

      - name: Exit quietly if none
        if: ${{ steps.find.outputs.count == '0' }}
        run: echo "No CLEAN PRs to merge. Exiting 0."

      - name: Merge PRs (squash + delete branch; allow auto)
        if: ${{ steps.find.outputs.count != '0' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          for pr in ${{ steps.find.outputs.prs }}; do
            echo "Merging #$pr…"
            gh pr merge "$pr" --squash --delete-branch --auto || true
          done
