name: Auto Merge Green PRs

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 7-19 * * 1-5"   # optional; keep or adjust
  pull_request:
    types: [synchronize, reopened, labeled, ready_for_review]
    paths-ignore:
      - '.github/workflows/**auto-merge**.yml'
      - '.github/workflows/**auto_merge**.yml'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-merge
  cancel-in-progress: false

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Do NOT run on PRs from forks, or on the PR that modifies this workflow
    if: >
      ${{
        github.event_name != 'pull_request' ||
        (
          github.event.pull_request.head.repo.full_name == github.repository &&
          !contains(github.event.pull_request.title, 'auto-merge')
        )
      }}
    steps:
      - uses: actions/checkout@v4

      - uses: cli/gh-action@v2

      - name: Find mergeable PRs
        id: find
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # gh prefers GH_TOKEN; GITHUB_TOKEN also works
        run: |
          set -euo pipefail
          # CLEAN = all checks green & mergeable
          prs="$(gh pr list --state open \
                 --json number,isDraft,mergeStateStatus \
                 --jq '.[] | select(.isDraft==false) | select(.mergeStateStatus==\"CLEAN\") | .number' \
                 || true)"
          echo "prs=${prs}" >> "$GITHUB_OUTPUT"
          count="$(wc -w <<<"$prs" | tr -d ' ')"
          echo "count=${count}" >> "$GITHUB_OUTPUT"
          echo "Found $count CLEAN PR(s)."

      - name: Exit quietly if none
        if: ${{ steps.find.outputs.count == '0' }}
        run: echo "No green PRs. Exiting 0."

      - name: Merge PRs (squash + delete branch; allow auto-merge)
        if: ${{ steps.find.outputs.count != '0' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          for pr in ${{ steps.find.outputs.prs }}; do
            echo "Merging #$pr…"
            gh pr merge "$pr" --squash --delete-branch --auto || true
          done
