name: Bulk PR Sync
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with: { ref: main, fetch-depth: 0 }
      - name: Fetch open PRs
        id: prs
        run: |
          curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&per_page=100" \
            > prs.json
          jq -r '.[].number' prs.json > pr_numbers.txt || true
          echo "Open PRs:"; cat pr_numbers.txt || true
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black isort flake8
      - name: Sync loop
        run: |
          set -e
          while read PR; do
            [ -z "$PR" ] && continue
            echo "=== Sync PR #$PR ==="
            BRANCH=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR" | jq -r '.head.ref')
            git fetch origin "$BRANCH":"$BRANCH"
            git checkout "$BRANCH"
            git merge --no-edit origin/main || true
            if git ls-files -u | grep -q "server/retention/sweeper.py"; then
              git checkout --theirs -- server/retention/sweeper.py || true
              git add server/retention/sweeper.py
              git commit -m "merge: adopt main's sweeper.py" || true
            fi
            pre-commit run --all-files || true
            git add -A
            if git diff --cached --quiet; then
              echo "No changes for $BRANCH"
            else
              git commit -m "chore: bulk sync $BRANCH with main and apply pre-commit"
              git push
            fi
            git checkout main
          done < pr_numbers.txt
