name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure test deps
          pip install numpy pytest
          [ -d "golfiq/cv-engine" ] && pip install -e golfiq/cv-engine
          pip install -r server/requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: "${{ github.workspace }}/golfiq/cv-engine:${{ github.workspace }}/golfiq/cv-engine/src"
        run: |
          pytest -q
