name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements-dev.txt
      - run: black --check .
      - run: flake8 .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt
          pip install -e . || true
      - name: Run tests (with coverage)
        run: pytest -q tests server/tests --cov=server --cov-report=xml
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
      - name: Coverage gate (PR)
        if: github.event_name == 'pull_request'
        run: python .github/scripts/coverage_gate.py pr --xml coverage.xml --tolerance 0.25
      - name: Update baseline & badge (main)
        if: github.ref == 'refs/heads/main'
        run: python .github/scripts/coverage_gate.py update --xml coverage.xml
      - name: Commit badge/baseline (main)
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "ci: update coverage badge & baseline"
          file_pattern: ".github/coverage-baseline.json README.md"
