name: CI
on:
  push:
  pull_request:
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt
      - name: Run lint
        run: |
          black --check .
          isort --check-only .
          flake8 .
      - name: Run pytest
        env:
          PYTHONPATH: "${{ github.workspace }}"
        run: pytest -q
