name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install lint deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          [ -d "golfiq/cv-engine" ] && pip install -e golfiq/cv-engine || true
          [ -f "server/requirements.txt" ] && pip install -r server/requirements.txt || true
          pip install pytest
      - name: Run pytest
        env:
          PYTHONPATH: "${{ github.workspace }}:${{ github.workspace }}/golfiq/cv-engine:${{ github.workspace }}/golfiq/cv-engine/src"
        run: pytest -q
