name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run lint
        run: |
          black --check .
          isort --check-only .
          flake8 .

  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          [ -d "golfiq/cv-engine" ] && pip install -e golfiq/cv-engine || true
          [ -f "server/requirements.txt" ] && pip install -r server/requirements.txt || true
      - name: Run pytest
        run: pytest -q

