name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt
      - name: Run lint
        run: |
          black --check .
          isort --check-only .
          flake8 .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt
          [ -d "golfiq/cv-engine" ] && pip install -e golfiq/cv-engine || true
          [ -f "server/requirements.txt" ] && pip install -r server/requirements.txt || true
      - name: Run tests
        env:
          PYTHONPATH: "${{ github.workspace }}:${{ github.workspace }}/golfiq/cv-engine:${{ github.workspace }}/golfiq/cv-engine/src"
        run: pytest -q
