name: Codex Runner

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Klistra in bash-skriptet som ska köras"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Kör Codex-task (materialisera och kör)
        shell: bash
        env:
          PAT: ${{ secrets.CODEX_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # Spara inputs.task exakt som du klistrat in (bevarar alla rader)
          cat > _task.sh <<'TASK'
          ${{ inputs.task }}
          TASK
          chmod +x _task.sh
          echo "---- PREVIEW (första 40 rader) ----"
          sed -n '1,40p' _task.sh || true
          echo "---- RUN ----"
          bash _task.sh
