name: Codex Runner
on:
  workflow_dispatch:
    inputs:
      task:
        description: "Bash script to run against this repo (multi-line)."
        required: true
        type: string
permissions:
  contents: write
  pull-requests: write
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.CODEX_PAT }}
      REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Tooling
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: Prepare git with PAT
        run: |
          git config user.name "codex-bot"
          git config user.email "bot@users.noreply.github.com"
          if [ -n "${PAT}" ]; then
            git remote set-url origin "https://x-access-token:${PAT}@github.com/${REPO}.git"
          fi
      - name: Run task
        shell: bash
        run: |
          cat > /tmp/task.sh <<'TASK'
          ${{ inputs.task }}
          TASK
          chmod +x /tmp/task.sh
          /bin/bash -eo pipefail /tmp/task.sh
