name: Codex Runner

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Shellscript att köra (bash). Klistra in kommandon här när du kör."
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Kör Codex-task
        shell: bash
        env:
          PAT: ${{ secrets.CODEX_PAT }}          # Läggs i Settings → Secrets → Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # Spara input som ett skript så även långa, flerradiga kommandon funkar
          cat > _task.sh <<'TASK'
          ${{ inputs.task }}
          TASK
          chmod +x _task.sh
          ./_task.sh

