name: cv-engine-coverage
on:
  pull_request:
    paths-ignore:
      - 'android/**'
      - 'ios/**'
  push:
    branches: [main]
    paths-ignore:
      - 'android/**'
      - 'ios/**'
jobs:
  cvengine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Run cv_engine tests with coverage (report-only)
        run: pytest -q cv_engine --cov=cv_engine --cov-report=xml || true
      - name: Upload cv_engine coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cv_engine-coverage-xml
          path: coverage.xml
