name: Edge Export & Micro Bench

on:
  pull_request:

jobs:
  edge-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy onnx onnxruntime

      - name: Install optional edge deps
        shell: bash
        run: |
          set -e
          python -m pip install coremltools || echo "coremltools unavailable"
          python -m pip install tflite-runtime || echo "tflite-runtime unavailable"

      - name: Run export harness (dry-run)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p logs
          python scripts/export_models.py --output-dir exports/ci --report models/EXPORT_REPORT.md --frames 16 --dry-run | tee logs/export.log

      - name: Upload export reports
        uses: actions/upload-artifact@v4
        with:
          name: edge-export-report
          path: |
            models/EXPORT_REPORT.md
            logs/
