name: edge-bench
on:
  pull_request:
    paths:
      - "scripts/export_models.py"
      - "models/**"
      - "tests/models/**"
      - ".github/workflows/edge-bench.yml"

jobs:
  onnx-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy onnx onnxruntime pytest
      - name: Run export script (ONNX)
        run: |
          python scripts/export_models.py --targets onnx --image-size 320 --iters 25 --report models/EXPORT_REPORT.md
      - name: Run tests
        run: pytest -q tests/models/test_export_sanity.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: edge-bench-report
          path: |
            models/EXPORT_REPORT.md
            models/tmp_tiny.onnx
