name: golden-regression

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  golden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt
      - name: Run golden regression tests
        run: pytest -q tests/golden/test_backview_golden.py
