name: ios-ci

on:
  pull_request:
    paths:
      - "ios/**"
      - "shared/arhud/**"
      - ".github/workflows/ios-ci.yml"

jobs:
  dry-run:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install CocoaPods
        run: brew install cocoapods
      - name: Pod install
        working-directory: ios
        run: pod install --repo-update
      - name: Detect scheme
        id: detect
        working-directory: ios
        run: |
          xcodebuild -list -json > ../xclist.json
          SCHEME=$(python3 - <<'PY'
          import json,sys
          j=json.load(open("../xclist.json"))
          s=j.get("workspace",{}).get("schemes") or j.get("project",{}).get("schemes") or []
          print(s[0] if s else "")
          PY
)
          echo "SCHEME=$SCHEME" >> $GITHUB_ENV
          if [ -z "$SCHEME" ]; then echo "No scheme found, skipping"; fi
      - name: Show Build Settings
        if: env.SCHEME != ''
        working-directory: ios
        run: xcodebuild -workspace *.xcworkspace -scheme "$SCHEME" -sdk iphonesimulator -configuration Debug -showBuildSettings > ../xcodebuild.log
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-logs
          path: |
            xcodebuild.log
            xclist.json
