name: ios-ci

on:
  pull_request:
    paths:
      - "ios/**"
      - "shared/arhud/**"
      - ".github/workflows/ios-ci.yml"

jobs:
  dry-run:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: CocoaPods
        run: brew install cocoapods
      - name: Pod install (no commit)
        working-directory: ios
        run: pod install --repo-update
      - name: Detect scheme
        id: detect
        working-directory: ios
        run: |
          xcodebuild -list -json > ../xclist.json
          python3 - <<'PY'
import json
j=json.load(open("../xclist.json"))
workspace=j.get("workspace", {})
project=j.get("project", {})
schemes=workspace.get("schemes") or project.get("schemes") or []
open("../scheme.txt", "w").write(schemes[0] if schemes else "")
PY
      - name: Show Build Settings (best effort)
        if: ${{ hashFiles('scheme.txt') != '' }}
        working-directory: ios
        run: xcodebuild -workspace *.xcworkspace -scheme "$(cat ../scheme.txt)" -sdk iphonesimulator -configuration Debug -showBuildSettings > ../xcodebuild.log
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-logs
          path: |
            xcodebuild.log
            xclist.json
            scheme.txt
          if-no-files-found: ignore
