name: PR Repair (install → test → auto-fix → push)
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to repair (e.g., 27)"
        required: true
        type: string
permissions:
  contents: write
  pull-requests: write
jobs:
  repair:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info
        id: pr
        run: |
          set -e
          PR=${{ inputs.pr_number }}
          curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR" > pr.json
          echo "head_ref=$(jq -r '.head.ref' pr.json)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pytest pre-commit
          [ -d "golfiq/cv-engine" ] && pip install -e golfiq/cv-engine || true
          [ -f "server/requirements.txt" ] && pip install -r server/requirements.txt || true
      - name: Run tests (first pass)
        env:
          PYTHONPATH: "${{ github.workspace }}:${{ github.workspace }}/golfiq/cv-engine:${{ github.workspace }}/golfiq/cv-engine/src"
        run: pytest -q || true
      - name: Run pre-commit (auto-fix) and update snapshots
        run: |
          pre-commit run --all-files || true
          git add -A
          git diff --cached --quiet || git commit -m "style: apply pre-commit fixes"
      - name: Push fixes
        run: git push
      - name: Comment on PR
        run: |
          PR=${{ inputs.pr_number }}
          MSG="PR #$PR repaired: deps installed, tests run, auto-fix tried."
          curl -s -H "Authorization: Bearer ${{ github.token }}" \
               -H "Accept: application/vnd.github+json" \
               -d "{\"body\":\"$MSG\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/$PR/comments"
