name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  IMAGE_REF: ghcr.io/${{ toLower(github.repository) }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE_REF }}
          tags: |
            type=ref,event=tag
            type=sha
            type=raw,value=latest
      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PY_IMAGE=python:3.11-slim
            VIDEO_EXTRAS=1
          cache-from: type=gha
          cache-to: type=gha,mode=max

  smoke-test:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull ${{ env.IMAGE_REF }}:latest
      - name: Run container
        run: |
          cid=$(docker run -d -e SERVE_WEB=0 -p 8000:8000 ${{ env.IMAGE_REF }}:latest)
          echo "$cid" > cid.txt
          sleep 5
      - name: Health check
        run: |
          curl -f http://localhost:8000/health || (docker logs $(cat cid.txt) && exit 1)
      - name: Cleanup
        if: always()
        run: docker rm -f $(cat cid.txt)
