name: static-analysis

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt
      - run: mypy .
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          pip install bandit
      - run: bandit -r server -x tests || bandit -r . -x tests
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          pip install pip-audit
          pip-audit -r requirements.txt || true
          pip-audit -r requirements-dev.txt || true
