name: Tag Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name (e.g., v0.9.0)"
        required: true
        type: string
permissions:
  contents: write
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Create tag
        run: |
          git config user.name "codex-bot"
          git config user.email "bot@users.noreply.github.com"
          git tag "${{ inputs.tag }}" -m "${{ inputs.tag }}"
          git push origin "${{ inputs.tag }}"
